"""
UTILITY SCRIPT: VISUALIZE ABLATION STUDY RESULTS

This script reads the 'ablation_study_results.csv' file generated by
'model_training.py' and creates a bar chart to visualize the impact
of excluding different feature groups on model performance.
"""

import pandas as pd
import matplotlib.pyplot as plt
import sys

# --- NEW: Make seaborn an optional dependency for prettier plots ---
try:
    import seaborn as sns
    SEABORN_INSTALLED = True
except ImportError:
    SEABORN_INSTALLED = False
# --- END NEW ---

RESULTS_CSV_FILE = "ablation_study_results.csv"
OUTPUT_PLOT_FILE = "ablation_study_plot.png"

# We focus on the blended model as it's typically the best performer
MODEL_TO_ANALYZE_KEYWORD = "Final" 

def visualize_ablation_results():
    """
    Loads the ablation study results and generates a bar chart comparing
    the R-squared scores for each run.
    """
    try:
        df = pd.read_csv(RESULTS_CSV_FILE)
    except FileNotFoundError:
        print(f"FATAL ERROR: Results file '{RESULTS_CSV_FILE}' not found.")
        print("Please run the ablation study in 'model_training.py' first.")
        sys.exit(1)

    # --- FIX: Filter for the 'Final' evaluation run, regardless of which model was best ---
    # This makes the visualization robust even if the best model changes between runs.
    analysis_df = df[df['model_name'].str.contains(MODEL_TO_ANALYZE_KEYWORD, case=False, na=False)].copy()

    if analysis_df.empty:
        print(f"FATAL ERROR: No 'Final' evaluation results found in '{RESULTS_CSV_FILE}'.")
        print("Please check the model names in the CSV file.")
        sys.exit(1)

    # The baseline is the run where no group was excluded
    baseline_row = analysis_df[analysis_df['excluded_group'] == 'none']
    if baseline_row.empty:
        print("FATAL ERROR: Baseline run (excluded_group = 'none') not found in the results.")
        sys.exit(1)
    
    baseline_r2 = baseline_row['r_squared'].iloc[0]

    # Prepare data for plotting
    plot_data = analysis_df.sort_values(by='r_squared', ascending=False)

    # --- Create the Plot ---
    if SEABORN_INSTALLED:
        plt.style.use('seaborn-v0_8-whitegrid')
        colors = sns.color_palette("viridis", len(plot_data))
    else:
        plt.style.use('default')
        colors = plt.cm.viridis([i/len(plot_data) for i in range(len(plot_data))])

    plt.figure(figsize=(12, 8))

    bars = plt.bar(plot_data['excluded_group'], plot_data['r_squared'], color=colors)

    # Add a horizontal line for the baseline score for easy comparison
    plt.axhline(y=baseline_r2, color='r', linestyle='--', linewidth=2, label=f'Baseline R² ({baseline_r2:.4f})')

    # Add labels and title
    plt.ylabel('R-squared Score (Higher is Better)', fontsize=14)
    plt.xlabel('Feature Group Excluded from Model', fontsize=14)
    plt.title('Ablation Study: Impact of Feature Groups on Model Performance', fontsize=16, weight='bold')
    plt.xticks(rotation=45, ha='right')
    plt.ylim(bottom=max(0, plot_data['r_squared'].min() - 0.05)) # Adjust y-axis to start near the lowest score
    plt.legend()
    plt.tight_layout() # Adjust layout to make room for labels

    # Save the plot
    plt.savefig(OUTPUT_PLOT_FILE)
    print(f"\n--- Visualization Complete ---")
    print(f"Ablation study plot saved to: {OUTPUT_PLOT_FILE}")

if __name__ == "__main__":
    visualize_ablation_results()
